### ISSUE TITLE
Declare explicit paths

### ISSUE THREAD

**Issue by rcmaehl** [builtbybel/ThisIsWin11#51]
I'm no C# programmer yet, but in

https://github.com/builtbybel/ThisIsWin11/blob/4fe005bc02845b56437bdbb258e10e0f721c1568/src/TIW11/Modules/OpenTweaks/WindowsHelper.cs#L22
and
https://github.com/builtbybel/ThisIsWin11/blob/4fe005bc02845b56437bdbb258e10e0f721c1568/src/TIW11/Modules/OpenTweaks/WindowsHelper.cs#L29

It appears that the powershell directory isn't being declared. This isn't safe. If the path isn't declared, Windows will first search the same directory as the executable before searching elsewhere. This would allow anyone to put a file named powershell.exe in the same directory and have it be ran, potentially with admin rights.

I personally got blasted by a couple security researchers for doing the same in WhyNotWin11 and would like to pass this warning on to you!

Keep up the good work, the app looks great!

**Comment by Belim** [comment]
Hey Robert

I assume you are referring to a DLL side-loading attack and the default Windows search order.

Yeah, this could indeed be optimised. Instead of having to call an external PS process the PowerShell SDK (API) > `System.Management.Automation `could be used. The easiest approach would be to set ` .UseShellExecute to true` and `.Verb set to RunAs`. I will look at this again.

Thank you first of all for the info and nice words. 😄  
🤔 but until now, this profession group has spared me 🤣

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/releases/tag/0.92.0
